parameters:

  # Twig templates
  templates:
    - './src/TaskManager/View'

  # Path to data file
  xml_location: data.xml

  # Database connection
  database_dsn: mysql:host=localhost;dbname=task-manager-dev;charset=utf8mb4
  database_user: root
  database_password: rootpassword