routes:
  home:
    pattern: '/'
    module: TaskManager
    controller: Task
    action: index
  task_list:
    pattern: '/tasks'
    module: TaskManager
    controller: Task
    action: index
  task_by_priority:
    pattern: '/tasks/(?!new|\d+)(\w+)'
    module: TaskManager
    controller: Task
    action: showByPriority
  task_single:
    pattern: '/tasks/(\d+)'
    module: TaskManager
    controller: Task
    action: show
  task_create:
    pattern: '/tasks/new'
    module: TaskManager
    controller: Task
    action: create
