services:

  twig_loader:
    class: Twig_Loader_Filesystem
    arguments:
      - '%templates'

  twig:
    class: Twig_Environment
    arguments:
      - '@twig_loader'

  pdo:
    class: PDO
    arguments:
      - '%database_dsn'
      - '%database_user'
      - '%database_password'

  app_extension:
    class: AppExtension
    arguments:
      - '%env'

  task_storage_in_memory:
    class: TaskManager\Storage\InMemory\TaskStorage

  task_storage_in_xml:
    class: TaskManager\Storage\InXml\TaskStorage
    arguments:
      - '%xml_location'

  task_storage_in_db:
    class: TaskManager\Storage\InDB\TaskStorage
    arguments:
      - '@pdo'